name: Build and deploy ASP.Net Core app to Azure Web App - websiteyn2ilar5pn7vk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ./myapp  # Output to a relative path

      - name: List files in the working directory
        run: dir  # Lists files to verify 'myapp' exists

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp  # Correct path to the published output

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: List files in the deployment job
        run: dir  # List files to verify the package is available
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8184779E632347F8A493FE46B68C5112 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FB53FC8E6DA847D5948F00418931CDDE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A6EE8E3A05A042C3BB67E9348C588F29 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'websiteyn2ilar5pn7vk'
          slot-name: 'Production'
          package: ./myapp  # Ensure this points to the correct package
